### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by jonasstein** [jbergstroem/gentoo-overlay#2]
Hi,
I sent you a mail to bugs at bergstroem nu recently. Did you receive the mail? Do you still want to maintain your packages as proxied maintainer?
https://bugs.gentoo.org/633054
As far I can see, you have been very active on bugzilla betweeen2016-02-06 and 2016-06-22 and then all of a sudden the activity stopped. Did your mail change? Did something happen?
I got no reply on bugzilla no reply on my mail and you were not active on your packages or bugzilla for a long time. Now I want to give it a last try by misusing your bug tracker. Best, Jonas

**Comment by jbergstroem** [comment]
Closing this since we've "solved" it in bugzilla/over email.
